In [1]:
# pastikan java sudah terinstal di vsc untuk membaca file pdf dan install tabula-py (library tabula)

from tabula import read_pdf
import pandas as pd

pdf_file = "bri.pdf"

# membaca tabel dari halaman pertama
df = read_pdf(pdf_file, pages=1, lattice=True)
print(df)

Failed to import jpype dependencies. Fallback to subprocess.
No module named 'jpype'

[                                           Unnamed: 0  \
0   LAPORAN POSISI KEUANGAN\rPT BANK RAKYAT INDONE...
1                                                 No.
2                                                 NaN
3                                                 NaN
4                                                ASET
..                                                ...
56                                                16.
57                                                NaN
58                                                NaN
59                                                NaN
60                                                NaN

                 Unnamed: 1                   Unnamed: 2  \
0                       NaN                          NaN
1                 POS - POS                   INDIVIDUAL
2   30 Juni 2023\r(Direviu)  31 Desember 2022\r(Diaudit)
3                       NaN                          NaN
4                       NaN                          NaN
..                      ...                          ...
56   Tambahan modal disetor                          NaN
57                   a.Agio                   76.240.176
58            b.Disagio -/-                            -
59     c.Dana setoran modal                            -
60                d.Lainnya                       39.870

                 Unnamed: 3                   Unnamed: 4  Unnamed: 5
0                       NaN                          NaN         NaN
1             KONSOLIDASIAN                          NaN         NaN
2   30 Juni 2023\r(Direviu)  31 Desember 2022\r(Diaudit)         NaN
3                       NaN                          NaN         NaN
4                       NaN                          NaN         NaN
..                      ...                          ...         ...
56                      NaN                          NaN         NaN
57               76.029.910                   75.847.349  75.637.083
58                        -                            -           -
59                        -                            -           -
60                  226.563                    1.798.450   1.985.202

[61 rows x 6 columns]]

In [2]:
# mengekstraksi banya tabel
# membaca semua tabel di halaman
tables = read_pdf(pdf_file, pages="all", multiple_tables=True, lattice=True)

# menampilkan jumlah tabel yang ditemukan
print(f"Ditemukan {len(tables)} tabel.")

# menamipilkan tabel pertama
print(tables[0])

Ditemukan 16 tabel.
                                           Unnamed: 0  \
0   LAPORAN POSISI KEUANGAN\rPT BANK RAKYAT INDONE...
1                                                 No.
2                                                 NaN
3                                                 NaN
4                                                ASET
..                                                ...
56                                                16.
57                                                NaN
58                                                NaN
59                                                NaN
60                                                NaN

                 Unnamed: 1                   Unnamed: 2  \
0                       NaN                          NaN
1                 POS - POS                   INDIVIDUAL
2   30 Juni 2023\r(Direviu)  31 Desember 2022\r(Diaudit)
3                       NaN                          NaN
4                       NaN                          NaN
..                      ...                          ...
56   Tambahan modal disetor                          NaN
57                   a.Agio                   76.240.176
58            b.Disagio -/-                            -
59     c.Dana setoran modal                            -
60                d.Lainnya                       39.870

                 Unnamed: 3                   Unnamed: 4  Unnamed: 5
0                       NaN                          NaN         NaN
1             KONSOLIDASIAN                          NaN         NaN
2   30 Juni 2023\r(Direviu)  31 Desember 2022\r(Diaudit)         NaN
3                       NaN                          NaN         NaN
4                       NaN                          NaN         NaN
..                      ...                          ...         ...
56                      NaN                          NaN         NaN
57               76.029.910                   75.847.349  75.637.083
58                        -                            -           -
59                        -                            -           -
60                  226.563                    1.798.450   1.985.202

[61 rows x 6 columns]

In [3]:
# menyimpan tabel ke csv
for i, table in enumerate(tables):
    csv_file = f"table_{i + 1}.csv"  # Nama file CSV untuk setiap tabel
    table.to_csv(csv_file, index=False)
    print(f"Tabel {i + 1} disimpan sebagai {csv_file}")

Tabel 1 disimpan sebagai table_1.csv
Tabel 2 disimpan sebagai table_2.csv
Tabel 3 disimpan sebagai table_3.csv
Tabel 4 disimpan sebagai table_4.csv
Tabel 5 disimpan sebagai table_5.csv
Tabel 6 disimpan sebagai table_6.csv
Tabel 7 disimpan sebagai table_7.csv
Tabel 8 disimpan sebagai table_8.csv
Tabel 9 disimpan sebagai table_9.csv
Tabel 10 disimpan sebagai table_10.csv
Tabel 11 disimpan sebagai table_11.csv
Tabel 12 disimpan sebagai table_12.csv
Tabel 13 disimpan sebagai table_13.csv
Tabel 14 disimpan sebagai table_14.csv
Tabel 15 disimpan sebagai table_15.csv
Tabel 16 disimpan sebagai table_16.csv

In [4]:
from tabula import read_pdf
import pandas as pd

pdf_file = "bri.pdf"

# ekstraksi data tabel
tables = read_pdf(pdf_file, pages="all", multiple_tables=True, lattice=True)

# menampilkan jumlah tabel yang ditemukan
print(f"Terdapat {len(tables)} tabel yang diekstrak.")

# ambil tabel aset (tabel pertama)
table_aset = tables[0]

# ambil tabel rasio kinerja (tabel kedua)
table_rasio = tables[1]

print(table_aset)
print(table_rasio)

Terdapat 16 tabel yang diekstrak.
                                           Unnamed: 0  \
0   LAPORAN POSISI KEUANGAN\rPT BANK RAKYAT INDONE...
1                                                 No.
2                                                 NaN
3                                                 NaN
4                                                ASET
..                                                ...
56                                                16.
57                                                NaN
58                                                NaN
59                                                NaN
60                                                NaN

                 Unnamed: 1                   Unnamed: 2  \
0                       NaN                          NaN
1                 POS - POS                   INDIVIDUAL
2   30 Juni 2023\r(Direviu)  31 Desember 2022\r(Diaudit)
3                       NaN                          NaN
4                       NaN                          NaN
..                      ...                          ...
56   Tambahan modal disetor                          NaN
57                   a.Agio                   76.240.176
58            b.Disagio -/-                            -
59     c.Dana setoran modal                            -
60                d.Lainnya                       39.870

                 Unnamed: 3                   Unnamed: 4  Unnamed: 5
0                       NaN                          NaN         NaN
1             KONSOLIDASIAN                          NaN         NaN
2   30 Juni 2023\r(Direviu)  31 Desember 2022\r(Diaudit)         NaN
3                       NaN                          NaN         NaN
4                       NaN                          NaN         NaN
..                      ...                          ...         ...
56                      NaN                          NaN         NaN
57               76.029.910                   75.847.349  75.637.083
58                        -                            -           -
59                        -                            -           -
60                  226.563                    1.798.450   1.985.202

[61 rows x 6 columns]
                                           Unnamed: 0  \
0   LAPORAN POSISI KEUANGAN\rPT BANK RAKYAT INDONE...
1                                                 No.
2                                                 NaN
3                                                 NaN
4                                                 17.
5                                                 NaN
6                                                 NaN
7                                                 18.
8                                                 NaN
9                                                 NaN
10                                                19.
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                20.
16                                                NaN
17                                                NaN
18                                                NaN
19                                                NaN

                                           Unnamed: 1  \
0                                                 NaN
1                                           POS - POS
2                             30 Juni 2023\r(Direviu)
3                                                 NaN
4                       Penghasilan komprehensif lain
5                                      a.\rKeuntungan
6                                    b.\rKerugian -/-
7                                            Cadangan
8                                     a.Cadangan umum
9                                   b.Cadangan tujuan
10                                          Laba/rugi
11                                 a.Tahun-tahun lalu
12                                   b.Tahun berjalan
13                      c.Dividen yang dibayarkan -/-
14  TOTAL EKUITAS YANG DAPAT DIATRIBUSIKAN KEPADA\...
15          Kepentingan minoritas (minority interest)
16                                                NaN
17                                      TOTAL EKUITAS
18                                                NaN
19                       TOTAL LIABILITAS DAN EKUITAS

                     Unnamed: 2               Unnamed: 3  \
0                           NaN                      NaN
1                    INDIVIDUAL            KONSOLIDASIAN
2   31 Desember 2022\r(Diaudit)  30 Juni 2023\r(Direviu)
3                           NaN                      NaN
4                           NaN                      NaN
5                    19.998.763               19.848.571
6                   (4.784.442)              (5.145.961)
7                           NaN                      NaN
8                     3.022.685                3.022.685
9                             -                        -
10                          NaN                      NaN
11                  159.372.471              146.436.494
12                   26.265.520               47.827.920
13                            -                        -
14                  284.713.860              293.621.954
15                            -                        -
16                          NaN                      NaN
17                  284.713.860              293.621.954
18                          NaN                      NaN
19                1.684.763.202            1.750.994.673

                     Unnamed: 4     Unnamed: 5
0                           NaN            NaN
1                           NaN            NaN
2   31 Desember 2022\r(Diaudit)            NaN
3                           NaN            NaN
4                           NaN            NaN
5                    20.374.608     19.472.883
6                   (4.760.186)    (4.346.863)
7                           NaN            NaN
8                     3.022.685      3.022.685
9                             -              -
10                          NaN            NaN
11                  163.255.306    146.976.937
12                   29.421.509     51.170.312
13                            -              -
14                  293.518.538    299.294.011
15                    4.973.148      4.101.306
16                          NaN            NaN
17                  298.491.686    303.395.317
18                          NaN            NaN
19                1.805.146.314  1.865.639.010

In [6]:
# cek struktur tabel aset
print(table_aset.head())  # menampilkan beberapa baris pertama
print(table_aset.columns)  # menampilkan nama kolom
print(len(table_aset.columns))  # menampilkan jumlah kolom

                                          Unnamed: 0               Unnamed: 1  \
0  LAPORAN POSISI KEUANGAN\rPT BANK RAKYAT INDONE...                        0
1                                                No.                POS - POS
2                                                  0  30 Juni 2023\r(Direviu)
3                                                  0                        0
4                                               ASET                        0

                    Unnamed: 2               Unnamed: 3  \
0                            0                        0
1                   INDIVIDUAL            KONSOLIDASIAN
2  31 Desember 2022\r(Diaudit)  30 Juni 2023\r(Direviu)
3                            0                        0
4                            0                        0

                    Unnamed: 4 Unnamed: 5
0                            0          0
1                            0          0
2  31 Desember 2022\r(Diaudit)          0
3                            0          0
4                            0          0
Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5'],
      dtype='object')
6

In [7]:
# hapus kolom tambahan jika ada
table_aset = table_aset.iloc[:, :5]  # hanya pilih 5 kolom pertama

In [8]:
# atur nama kolom
table_aset.columns = ["POS", "Individual 30 June 2023", "Individual 31 December 2022", "Consolidated 30 June 2023", "Consolidated 31 December 2022"]

In [9]:
# cek dataframe
print(table_aset.info())  # cek tipe data dan kolom
print(table_aset.head())  # cek data awal

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 5 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   POS                            61 non-null     object
 1   Individual 30 June 2023        61 non-null     object
 2   Individual 31 December 2022    61 non-null     object
 3   Consolidated 30 June 2023      61 non-null     object
 4   Consolidated 31 December 2022  61 non-null     object
dtypes: object(5)
memory usage: 2.5+ KB
None
                                                 POS  Individual 30 June 2023  \
0  LAPORAN POSISI KEUANGAN\rPT BANK RAKYAT INDONE...                        0
1                                                No.                POS - POS
2                                                  0  30 Juni 2023\r(Direviu)
3                                                  0                        0
4                                               ASET                        0

   Individual 31 December 2022 Consolidated 30 June 2023  \
0                            0                         0
1                   INDIVIDUAL             KONSOLIDASIAN
2  31 Desember 2022\r(Diaudit)   30 Juni 2023\r(Direviu)
3                            0                         0
4                            0                         0

  Consolidated 31 December 2022
0                             0
1                             0
2   31 Desember 2022\r(Diaudit)
3                             0
4                             0

In [11]:
print(table_aset.head())  # Lihat baris awal tabel
print(table_aset.dtypes)  # Periksa tipe data di setiap kolom

                                                 POS  Individual 30 June 2023  \
0  LAPORAN POSISI KEUANGAN\rPT BANK RAKYAT INDONE...                        0
1                                                No.                POS - POS
2                                                  0  30 Juni 2023\r(Direviu)
3                                                  0                        0
4                                               ASET                        0

   Individual 31 December 2022 Consolidated 30 June 2023  \
0                            0                         0
1                   INDIVIDUAL             KONSOLIDASIAN
2  31 Desember 2022\r(Diaudit)   30 Juni 2023\r(Direviu)
3                            0                         0
4                            0                         0

  Consolidated 31 December 2022
0                             0
1                             0
2   31 Desember 2022\r(Diaudit)
3                             0
4                             0
POS                              object
Individual 30 June 2023          object
Individual 31 December 2022      object
Consolidated 30 June 2023        object
Consolidated 31 December 2022    object
dtype: object